package Formulario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class jfrmC extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmC.class.getName());

    /**
     * Creates new form jfrmC
     */
    //variables restringuidas
        private String entrada="";
        private int numero1,numero2;
        private String operador;
    public jfrmC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtndivision = new javax.swing.JButton();
        jbtnmultiplicacion = new javax.swing.JButton();
        jbtnresta = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnigual = new javax.swing.JButton();
        jbtnAC = new javax.swing.JButton();
        jbtnsuma = new javax.swing.JButton();
        jbtnpunto = new javax.swing.JButton();
        jbtnporcentaje = new javax.swing.JButton();
        jbtnborra = new javax.swing.JButton();
        jbtnraiz = new javax.swing.JButton();

        jButton7.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jtxtCantidad.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jtxtCantidad.setCaretColor(new java.awt.Color(153, 153, 153));
        jtxtCantidad.setSelectionColor(new java.awt.Color(153, 153, 153));

        jbtnNum7.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum7.setText("7");
        jbtnNum7.addActionListener(this::jbtnNum7ActionPerformed);

        jbtnNum8.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum8.setText("8");
        jbtnNum8.addActionListener(this::jbtnNum8ActionPerformed);

        jbtnNum9.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum9.setText("9");
        jbtnNum9.addActionListener(this::jbtnNum9ActionPerformed);

        jbtnNum6.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum6.setText("6");
        jbtnNum6.addActionListener(this::jbtnNum6ActionPerformed);

        jbtnNum5.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum5.setText("5");
        jbtnNum5.addActionListener(this::jbtnNum5ActionPerformed);

        jbtnNum4.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum4.setText("4");
        jbtnNum4.addActionListener(this::jbtnNum4ActionPerformed);

        jbtnNum1.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum1.setText("1");
        jbtnNum1.addActionListener(this::jbtnNum1ActionPerformed);

        jbtnNum2.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum2.setText("2");
        jbtnNum2.addActionListener(this::jbtnNum2ActionPerformed);

        jbtnNum3.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum3.setText("3");
        jbtnNum3.addActionListener(this::jbtnNum3ActionPerformed);

        jbtndivision.setBackground(new java.awt.Color(204, 204, 204));
        jbtndivision.setText("/");
        jbtndivision.addActionListener(this::jbtndivisionActionPerformed);

        jbtnmultiplicacion.setBackground(new java.awt.Color(204, 204, 204));
        jbtnmultiplicacion.setText("x");
        jbtnmultiplicacion.addActionListener(this::jbtnmultiplicacionActionPerformed);

        jbtnresta.setBackground(new java.awt.Color(204, 204, 204));
        jbtnresta.setText("-");
        jbtnresta.addActionListener(this::jbtnrestaActionPerformed);

        jbtnNum0.setBackground(new java.awt.Color(204, 204, 204));
        jbtnNum0.setText("0");
        jbtnNum0.addActionListener(this::jbtnNum0ActionPerformed);

        jbtnigual.setBackground(new java.awt.Color(153, 153, 153));
        jbtnigual.setText("=");
        jbtnigual.addActionListener(this::jbtnigualActionPerformed);

        jbtnAC.setBackground(new java.awt.Color(204, 204, 204));
        jbtnAC.setText("AC");
        jbtnAC.addActionListener(this::jbtnACActionPerformed);

        jbtnsuma.setBackground(new java.awt.Color(204, 204, 204));
        jbtnsuma.setText("+");
        jbtnsuma.addActionListener(this::jbtnsumaActionPerformed);

        jbtnpunto.setBackground(new java.awt.Color(204, 204, 204));
        jbtnpunto.setText(".");
        jbtnpunto.addActionListener(this::jbtnpuntoActionPerformed);

        jbtnporcentaje.setBackground(new java.awt.Color(204, 204, 204));
        jbtnporcentaje.setText("%");
        jbtnporcentaje.addActionListener(this::jbtnporcentajeActionPerformed);

        jbtnborra.setBackground(new java.awt.Color(204, 204, 204));
        jbtnborra.setText("c");
        jbtnborra.addActionListener(this::jbtnborraActionPerformed);

        jbtnraiz.setBackground(new java.awt.Color(204, 204, 204));
        jbtnraiz.setText("v");
        jbtnraiz.addActionListener(this::jbtnraizActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtnNum7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(jbtnNum4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jbtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jbtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnborra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNum3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jbtnNum6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNum9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnigual, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnraiz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnmultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndivision, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnresta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnpunto)
                    .addComponent(jbtnporcentaje)
                    .addComponent(jbtnborra)
                    .addComponent(jbtnraiz))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum8)
                    .addComponent(jbtnNum7)
                    .addComponent(jbtnNum9)
                    .addComponent(jbtndivision))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum6)
                    .addComponent(jbtnNum5)
                    .addComponent(jbtnNum4)
                    .addComponent(jbtnmultiplicacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum2)
                    .addComponent(jbtnNum1)
                    .addComponent(jbtnNum3)
                    .addComponent(jbtnresta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum0)
                    .addComponent(jbtnAC)
                    .addComponent(jbtnsuma)
                    .addComponent(jbtnigual))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+7;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        // TODO add your handling code here:
        entrada=entrada+1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivisionActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="/";
        jtxtCantidad.setText(entrada);
       
    }//GEN-LAST:event_jbtndivisionActionPerformed

    private void jbtnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrestaActionPerformed
        // TODO add your handling code here:
         numero1=Integer.parseInt(entrada);
        entrada="";
        operador="-";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnrestaActionPerformed

    private void jbtnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplicacionActionPerformed
        // TODO add your handling code here:
         numero1=Integer.parseInt(entrada);
        entrada="";
        operador="x";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnmultiplicacionActionPerformed

    private void jbtnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnigualActionPerformed
         // TODO add your handling code here:
        double resultado;
        numero2=Integer.parseInt(entrada);
        jtxtCantidad.setText("");
        entrada="";
        
        if (operador.equals("*")) {
            resultado=numero1*numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        if(operador.equals("-")){
        resultado=numero1-numero2;
        entrada=String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
        }
        if(operador.equals("/")){
        resultado=numero1/numero2;
        entrada=String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
        }
        if(operador.equals("+")){
        resultado=numero1+numero2;
        entrada=String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtnigualActionPerformed

    private void jbtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnACActionPerformed
        // TODO add your handling code here:
            entrada="";
    numero1 = 0;
    numero2 = 0;
    jtxtCantidad.setText("0");
    }//GEN-LAST:event_jbtnACActionPerformed

    private void jbtnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpuntoActionPerformed
        // TODO add your handling code here:
         if (!entrada.contains(".")) {
         if (entrada.equals("")) {
             entrada = "0.";
         } else {
             entrada = entrada + ".";
         }
         jtxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtnpuntoActionPerformed

    private void jbtnporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnporcentajeActionPerformed
        // TODO add your handling code here:
         double valor = Double.parseDouble(entrada);
    valor = valor / 100;
    entrada = String.valueOf(valor);
    jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnporcentajeActionPerformed

    private void jbtnborraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnborraActionPerformed
        // TODO add your handling code here:
         if (entrada.length() > 1) {
        entrada = entrada.substring(0, entrada.length() -  1);
    } else {
            entrada = "";
    }
        
    if (entrada.equals("")) {
        jtxtCantidad.setText("0");
    } else {
        jtxtCantidad.setText(entrada);
    }
    }//GEN-LAST:event_jbtnborraActionPerformed

    private void jbtnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnraizActionPerformed
        // TODO add your handling code here
          double valor = Double.parseDouble(entrada);
        
    if (valor >= 0) {
        valor = Math.sqrt(valor);
        entrada = String.valueOf(valor);
    } else {
        entrada = "Error";
    }
    
    jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnraizActionPerformed

    private void jbtnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumaActionPerformed
        // TODO add your handling code here:}
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="+";
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_jbtnsumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jbtnAC;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnborra;
    private javax.swing.JButton jbtndivision;
    private javax.swing.JButton jbtnigual;
    private javax.swing.JButton jbtnmultiplicacion;
    private javax.swing.JButton jbtnporcentaje;
    private javax.swing.JButton jbtnpunto;
    private javax.swing.JButton jbtnraiz;
    private javax.swing.JButton jbtnresta;
    private javax.swing.JButton jbtnsuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
